### ISSUE TITLE
Order posts by categories without changing page

### ISSUE THREAD

**Issue by annehilliger** [weareopen/learnwith#5]
https://learnwith.weareopen.coop/knowledge-pool/tools/

there is a little dropdown to order the posts by tags but it changes to a new site. it would be nice if everything could happen on the tools & approaches site.

**Comment by dajbelshaw** [comment]
I think we need something like this ('faceted search') which isn't $99/year! https://facetwp.com

**Comment by annehilliger** [comment]
It is not perfecly solved but good enough for now so I will close this issue.
